version: "3"
services:
    server:
      build: ./serverApp
      ports:
        - "2000:2000"
      volumes:
        - ./serverApp/src:/app/src
    client:
      build: ./clientApp
      ports:
        - "3000:3000"
      volumes:
        - ./clientApp/src:/app/src
# volumes:
#  sshServer:
#    driver: vieux/sshfs:latest
#    driver_opts:
#      sshcmd: "server@192.168.1.52:/home/server/app/server"
#      password: "123456"
#      allow_other: ""
#  sshClient:
#    driver: vieux/sshfs:latest
#    driver_opts:
#      sshcmd: "server@192.168.1.52:/home/server/app/client"
#      password: "123456"
#      allow_other: ""
